### ISSUE TITLE
With my solid experience and passion for technology, I am enthusiastic about the opportunity to contribute to your team.

### ISSUE THREAD

**Issue by johnsmith0212** [canvas-ai/canvas#1]
Hi, I'm Ethan Tan, a web full-stack and blockchain developer with extensive experience spanning over 8 years. I specialize in developing resilient, scalable web applications and state-of-the-art blockchain solutions. My expertise in frameworks like React.js, Vue.js, and Next.js, along with my proficiency in Solidity for smart contract development, ensures I deliver premium, secure, and efficient solutions tailored to your specific needs.

**Comment by idncsk** [comment]
Hi, nice to meet you, I'll be adding tasks for the frontend part soon, will close this issue to keep the "root" project clean

**Comment by johnsmith0212** [comment]
thank you for your reply
If you need developer, plz contact me

-Contact Info
skype: https://join.skype.com/invite/FVUI6gLcYgAE
telegram: https://t.me/ethantan1116
slack: https://join.slack.com/t/ksc-xme4972/shared_invite/zt-2ld45idp2-G9HkxP_wX4ctwQshyPM7Ig
discord: https://discord.gg/VxnfdY4bS4
